# Kapital
eigenkapital: 70000
kaufpreis: 350000
modernisierung: 5000

# Nebenkosten
grunderwerbsteuer: 0.035
notar: 0.02
makler: 0.0357

# Kredit
annuitat: 1300.0
zinssatzJahrlich: 0.0374
zinsbindungJahre: 15.0

# Logging
loglevel: DEBUG
